In [1]:
#Importing required libraries

import pandas as pd 
import numpy as np 
from sklearn.preprocessing import StandardScaler 
from sklearn.linear_model  import Ridge,Lasso,RidgeCV, LassoCV, ElasticNet, ElasticNetCV, LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
#Creating adjusted R function

def adj_r2(x,y):
    r2 = regression.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [3]:

data= pd.read_csv('Admission_Prediction.csv')
data.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0           1      337.0        118.0                4.0  4.5  4.5  9.65   
1           2      324.0        107.0                4.0  4.0  4.5  8.87   
2           3        NaN        104.0                3.0  3.0  3.5  8.00   
3           4      322.0        110.0                3.0  3.5  2.5  8.67   
4           5      314.0        103.0                2.0  2.0  3.0  8.21   

   Research  Chance of Admit  
0         1             0.92  
1         1             0.76  
2         1             0.72  
3         1             0.80  
4         0             0.65

In [4]:
data.describe(include='all')

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  485.000000   490.000000         485.000000  500.000000   
mean   250.500000  316.558763   107.187755           3.121649    3.374000   
std    144.481833   11.274704     6.112899           1.146160    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  308.000000   103.000000           2.000000    2.500000   
50%    250.500000  317.000000   107.000000           3.000000    3.500000   
75%    375.250000  325.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

             LOR        CGPA    Research  Chance of Admit  
count  500.00000  500.000000  500.000000        500.00000  
mean     3.48400    8.576440    0.560000          0.72174  
std      0.92545    0.604813    0.496884          0.14114  
min      1.00000    6.800000    0.000000          0.34000  
25%      3.00000    8.127500    0.000000          0.63000  
50%      3.50000    8.560000    1.000000          0.72000  
75%      4.00000    9.040000    1.000000          0.82000  
max      5.00000    9.920000    1.000000          0.97000

In [5]:
#data['University Rating'] = data['University Rating'].fillna(data['University Rating'].mode()[0])
data['University Rating'] = data['University Rating'].fillna(data['University Rating'].mode()[0])
#data['TOEFL Score'] = data['TOEFL Score'].fillna(data['TOEFL Score'].mean())
data['TOEFL Score'] = data['TOEFL Score'].fillna(data['TOEFL Score'].mean())
#data['GRE Score'] = data['GRE Score'].fillna(data['GRE Score'].mean())
data['GRE Score'] = data['GRE Score'].fillna(data['GRE Score'].mean())


In [6]:
data.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [7]:
data['University Rating'].unique()

array([4., 3., 2., 5., 1.])

In [8]:
data.describe()

Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  500.000000   500.000000         500.000000  500.000000   
mean   250.500000  316.558763   107.187755           3.118000    3.374000   
std    144.481833   11.103952     6.051338           1.128993    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  309.000000   103.000000           2.000000    2.500000   
50%    250.500000  316.558763   107.000000           3.000000    3.500000   
75%    375.250000  324.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

             LOR        CGPA    Research  Chance of Admit  
count  500.00000  500.000000  500.000000        500.00000  
mean     3.48400    8.576440    0.560000          0.72174  
std      0.92545    0.604813    0.496884          0.14114  
min      1.00000    6.800000    0.000000          0.34000  
25%      3.00000    8.127500    0.000000          0.63000  
50%      3.50000    8.560000    1.000000          0.72000  
75%      4.00000    9.040000    1.000000          0.82000  
max      5.00000    9.920000    1.000000          0.97000

In [12]:
data.head(5)

Serial No.   GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0           1  337.000000        118.0                4.0  4.5  4.5  9.65   
1           2  324.000000        107.0                4.0  4.0  4.5  8.87   
2           3  316.558763        104.0                3.0  3.0  3.5  8.00   
3           4  322.000000        110.0                3.0  3.5  2.5  8.67   
4           5  314.000000        103.0                2.0  2.0  3.0  8.21   

   Research  Chance of Admit  
0         1             0.92  
1         1             0.76  
2         1             0.72  
3         1             0.80  
4         0             0.65

In [9]:
data= data.drop(columns = ['Serial No.'])
data.head(5)

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0  337.000000        118.0                4.0  4.5  4.5  9.65         1   
1  324.000000        107.0                4.0  4.0  4.5  8.87         1   
2  316.558763        104.0                3.0  3.0  3.5  8.00         1   
3  322.000000        110.0                3.0  3.5  2.5  8.67         1   
4  314.000000        103.0                2.0  2.0  3.0  8.21         0   

   Chance of Admit  
0             0.92  
1             0.76  
2             0.72  
3             0.80  
4             0.65

In [10]:
y = data['Chance of Admit']
X =data.drop(columns = ['Chance of Admit'])
#data.head()
#X


In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled= scaler.fit_transform(X)

In [12]:
X_scaled

array([[ 1.84274116e+00,  1.78854223e+00,  7.82009548e-01, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [ 6.70814288e-01, -3.10581135e-02,  7.82009548e-01, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [ 5.12433309e-15, -5.27312752e-01, -1.04622593e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.21170361e+00,  2.11937866e+00,  1.66864169e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [-4.10964364e-01, -6.92730965e-01,  7.82009548e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 9.41258951e-01,  9.61451165e-01,  7.82009548e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [13]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
variables = X_scaled

vif=pd.DataFrame()
vif["VIF"]=[variance_inflation_factor(variables,i)for i in range(variables.shape[1])]
vif["Features"]= X.columns

In [14]:
vif


VIF           Features
0  4.152735          GRE Score
1  3.793345        TOEFL Score
2  2.517272  University Rating
3  2.776393                SOP
4  2.037449                LOR
5  4.654369               CGPA
6  1.459411           Research

In [15]:
data.isna().sum()

GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [16]:
x_train,x_test,y_train,y_test = train_test_split(X_scaled,y,test_size = 0.25,random_state=355)

In [17]:
y_train

378    0.56
23     0.95
122    0.57
344    0.47
246    0.72
       ... 
51     0.56
291    0.56
346    0.47
130    0.96
254    0.85
Name: Chance of Admit, Length: 375, dtype: float64

In [18]:
from sklearn.linear_model import Ridge,Lasso,RidgeCV, LassoCV, ElasticNet, ElasticNetCV, LinearRegression
regression = LinearRegression()

regression.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
#Saving the model to local file system
import pickle
filename= "FinalisedModel.pickle"
pickle.dump(regression, open(filename, 'wb'))

In [20]:
#Saving the scaler model

filename1 ="ScalerModel.pickle"
pickle.dump(scaler, open(filename1, 'wb'))

In [46]:
#prediction using saved model

loaded_model =pickle.load(open(filename,'rb'))
a=loaded_model.predict(scaler.transform([[300,120,5,5,5,10,1]]))
a

array([0.94054361])

In [22]:
#Calculating value of Rsquare of training data
regression.score(x_train,y_train)

0.8415250484247909

In [23]:
#Calculating value of Adjusted Rsquare of Training data
adj_r2(x_train,y_train)

0.8385023654247188

In [24]:
#Calculating value of Rsquare for Testing Data

regression.score(x_test,y_test)

0.7534898831471066

In [25]:
#Calculating value of Rsquare for Testing Data

adj_r2(x_test,y_test)

0.7387414146174464

In [26]:
# Lasso Regularization
# LassoCV will return best alpha and coefficients after performing 10 cross validations
lasscv = LassoCV(alphas = None,cv =10, max_iter = 100000, normalize = True)
lasscv.fit(x_train, y_train)

LassoCV(alphas=None, copy_X=True, cv=10, eps=0.001, fit_intercept=True,
        max_iter=100000, n_alphas=100, n_jobs=None, normalize=True,
        positive=False, precompute='auto', random_state=None,
        selection='cyclic', tol=0.0001, verbose=False)

In [27]:
# best alpha parameter
alpha = lasscv.alpha_
alpha

3.0341655445178153e-05

In [28]:
#now that we have best parameter, let's use Lasso regression and see how well our data has fitted before

lasso_reg = Lasso(alpha)
lasso_reg.fit(x_train, y_train)

Lasso(alpha=3.0341655445178153e-05, copy_X=True, fit_intercept=True,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [29]:
lasso_reg.score(x_test, y_test)

0.7534654960492284

In [30]:
# Using Ridge regression model
# RidgeCV will return best alpha and coefficients after performing 10 cross validations. 
# We will pass an array of random numbers for ridgeCV to select best alpha from them

alphas = np.random.uniform(low=0, high=10, size=(50,))
ridgecv = RidgeCV(alphas = alphas,cv=10,normalize = True)
ridgecv.fit(x_train, y_train)

C:\Users\Harshit Kumar Pandey\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


RidgeCV(alphas=array([2.10352032, 2.21238533, 0.84368636, 9.0022861 , 6.29311088,
       7.69491634, 3.18181819, 2.57521032, 6.02401052, 0.17323999,
       5.53249766, 5.82893077, 6.6638542 , 6.02923549, 7.63443878,
       4.3342791 , 9.78623826, 9.17493953, 3.17217554, 7.73447005,
       1.54596016, 8.33692143, 2.23592877, 7.04030279, 6.26158556,
       2.62746962, 4.17175017, 0.12459031, 1.64028057, 3.15153224,
       9.56576237, 5.07283212, 0.54810415, 5.63766433, 6.72330542,
       5.67368243, 6.03087961, 8.46128054, 0.04269215, 8.05486485,
       8.95131696, 4.57547873, 7.8153404 , 3.65538105, 4.95605327,
       6.93214634, 2.85823663, 5.61946122, 6.95911217, 5.32603686]),
        cv=10, fit_intercept=True, gcv_mode=None, normalize=True, scoring=None,
        store_cv_values=False)

In [31]:
ridgecv.alpha_

0.042692151386753974

In [32]:
ridge_model = Ridge(alpha=ridgecv.alpha_)
ridge_model.fit(x_train, y_train)

Ridge(alpha=0.042692151386753974, copy_X=True, fit_intercept=True,
      max_iter=None, normalize=False, random_state=None, solver='auto',
      tol=0.001)

In [33]:
ridge_model.score(x_test, y_test)

0.7535108347626266

In [34]:
# Elastic net

elasticCV = ElasticNetCV(alphas = None, cv =10)

elasticCV.fit(x_train, y_train)

ElasticNetCV(alphas=None, copy_X=True, cv=10, eps=0.001, fit_intercept=True,
             l1_ratio=0.5, max_iter=1000, n_alphas=100, n_jobs=None,
             normalize=False, positive=False, precompute='auto',
             random_state=None, selection='cyclic', tol=0.0001, verbose=0)

In [35]:
elasticCV.alpha_

0.0011069728449315521

In [36]:
# l1_ration gives how close the model is to L1 regularization, below value indicates we are giving equal
#preference to L1 and L2
elasticCV.l1_ratio

0.5

In [37]:
elasticnet_reg = ElasticNet(alpha = elasticCV.alpha_,l1_ratio=0.5)
elasticnet_reg.fit(x_train, y_train)

ElasticNet(alpha=0.0011069728449315521, copy_X=True, fit_intercept=True,
           l1_ratio=0.5, max_iter=1000, normalize=False, positive=False,
           precompute=False, random_state=None, selection='cyclic', tol=0.0001,
           warm_start=False)

In [38]:
elasticnet_reg.score(x_test, y_test)

0.7531695370639867